```{r, include=FALSE}
library(tidyverse)
```

```{r, include=FALSE}
data <- read_table("A18-sjalv-win.dat",
                   col_names = c("län", "y1", "y2", "x51", "x41", "x52", "x42",
                                 "x11", "x12", "x61", "x62", "x21", "x22", "x3"))

data_1 <- data %>%
  select("län", "y1", "x51", "x41", "x11", "x61", "x21", "x3") %>%
  rename("län" = "län",
         "självmordsfrekvens" = "y1",
         "arbetslöshetsindex_män" = "x51",
         "arbetslöshetsindex_total" = "x41",
         "alkoholindex" = "x11",
         "urbaniseringsindex" = "x61",
         "skilsmässoindex" = "x21",
         "religiositetsindex" = "x3")

data_2 <- data %>%
  select("län", "y2", "x52", "x42", "x12", "x62", "x22", "x3") %>%
  rename("län" = "län",
         "självmordsfrekvens" = "y2",
         "arbetslöshetsindex_män" = "x52",
         "arbetslöshetsindex_total" = "x42",
         "alkoholindex" = "x12",
         "urbaniseringsindex" = "x62",
         "skilsmässoindex" = "x22",
         "religiositetsindex" = "x3")

save(data_1, file = "data_1.Rda")
save(data_2, file = "data_2.Rda")
```

```{r}
model_1 <- lm(data = data_1, självmordsfrekvens ~ arbetslöshetsindex_män +
                arbetslöshetsindex_total + alkoholindex + urbaniseringsindex +
                skilsmässoindex + religiositetsindex)
summary(model_1)
```


```{r}
model_2 <- lm(data = data_2, självmordsfrekvens ~ arbetslöshetsindex_män +
                arbetslöshetsindex_total + alkoholindex + urbaniseringsindex +
                skilsmässoindex + religiositetsindex)
summary(model_2)
```

```{r}
pairs(data_1, 3:8)
```



