---
title: "Projekt A MT5016"
author: "Betty Frankl"
date: "`r Sys.Date()`"
output: pdf_document
---

## Projekt A

```{r, include=FALSE}
library(car)
library(knitr)
library(tidyverse)

load("data_1.Rda")
load("data_2.Rda")

data_1 <- data_1 %>% select(!län)
data_2 <- data_2 %>% select(!län)
```

```{r, code = readLines("modeller.R"), include=FALSE}

```





```{r, include=FALSE}
# Functions

basic_plots <- function(data, model, title) {
  par(mfrow = c(2,3), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
  plot(data$arblös_män, data$sjmo,
       xlab = "arbetslöshetsindex män",
       ylab = "självmordsfrekvens",
       main = "Arbetslöshet män")
  plot(data$arblös_tot, data$sjmo,
       xlab = "arbetslöshetsindex total",
       ylab = "",
       main = "Arbetslöshet total")
  plot(data$alko, data$sjmo,
       xlab = "alkoholindex",
       ylab = "",
       main = "Alkohol")
  plot(data$urban, data$sjmo,
       xlab = "urbaniseringsindex",
       ylab = "självmordsfrekvens",
       main = "Urbanisering")
  plot(data$skilsmässo, data$sjmo,
       xlab = "skilsmässoindex",
       ylab = "",
       main = "Skilsmässor")
  plot(data$religio, data$sjmo,
       xlab = "religiositetsindex",
       ylab = "",
       main = "Religiositet")
  
  mtext(title, side = 3, line = -1, outer = TRUE, font = 2)
}

plot_predicted_residuals <- function(multi_model, title) {
  plot(multi_model$fitted.values, multi_model$residuals,
       xlab = "predikterade värden",
       ylab = "residualer",
       main = title)
  abline(0,0, col = "#0299b0", lwd=1.4)
} 

plot_multi_residuals <- function(data, multi_model, title) {
  par(mfrow = c(2,3))
  plot(residuals(multi_model) ~ data$arblös_män, 
       xlab = "arbetslöshetsindex män",
       ylab = "residuals",
       main = "Spread of residuals")
  abline(0,0) 
  plot(residuals(multi_model) ~ data$arblös_tot, 
       xlab = "arbetslöshetsindex total",
       ylab = "residuals",
       main = "Spread of residuals")
  abline(0,0) 
  plot(residuals(multi_model) ~ data$alko, 
       xlab = "alkoholindex",
       ylab = "residuals",
       main = "Spread of residuals")
  abline(0,0) 
  plot(residuals(multi_model) ~ data$urban, 
       xlab = "urbaniseringsindex",
       ylab = "residuals",
       main = "Spread of residuals")
  abline(0,0) 
  plot(residuals(multi_model) ~ data$skilsmässo, 
       xlab = "skilsmässoindex",
       ylab = "residuals",
       main = "Spread of residuals")
  abline(0,0) 
  plot(residuals(multi_model) ~ data$religio, 
       xlab = "religiositetsindex",
       ylab = "residuals",
       main = "Spread of residuals")
  abline(0,0)
  
  mtext(title, side = 3, line = 0, outer = TRUE)
}

plot_qq <- function(multi_model, title) {
  qqnorm(residuals(multi_model), 
         xlab = "teoretiska kvantiler",
         ylab = "datakvantiler",
         main = title)
  qqline(residuals(multi_model), col = "#ad465c", lwd=1.4)
}
```

```{r, include=FALSE}
sm_arb_män1 <- lm(sjmo ~ arblös_män, data = data_1)
sm_arb_tot1 <- lm(sjmo ~ arblös_tot, data = data_1)
sm_alk1 <- lm(sjmo ~ alko, data = data_1)
sm_urb1 <- lm(sjmo ~ urban, data = data_1)
sm_ski1 <- lm(sjmo ~ skilsmässo, data = data_1)
sm_rel1 <- lm(sjmo ~ religio, data = data_1)

sm_arb_män2 <- lm(sjmo ~ arblös_män, data = data_2)
sm_arb_tot2 <- lm(sjmo ~ arblös_tot, data = data_2)
sm_alk2 <- lm(sjmo ~ alko, data = data_2)
sm_urb2 <- lm(sjmo ~ urban, data = data_2)
sm_ski2 <- lm(sjmo ~ skilsmässo, data = data_2)
sm_rel2 <- lm(sjmo ~ religio, data = data_2)
```

```{r, echo=FALSE}
summary(sm_arb_män2)
summary(sm_arb_tot2)
summary(sm_alk1)
summary(sm_ski1)
```

```{r}
kable(cbind(c("Förklarande variabel", 
              "arbetslöshetsindex_män",
              "arbetslöshetsindex_total",
              "alkoholindex",
              "skilsmässoindex"),
            c("P-värde",
              "0.014",
              "0.0022",
              "0.00013",
              "0.0024")))
```

# Överblicka datan 

```{r}
basic_plots(data_2, model_2, "Plottar för respektive förklarande variabel mot självmordsfrekvens")
```

# Översiks residualer period 1

```{r, echo=FALSE, fig.cap="Plotten med residualer mot predikterade värden ser bra ut, punkterna har en jämn spridning längs residualer = 0, med andra ord verkar det finnas en homoskedasticitet. Normal QQ-plotten ser också bra ut, residualerna ser approximativt normalfördelade ut."}
par(mfrow = c(1,2), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
plot_predicted_residuals(model_1, "Mot predikterade")
plot_qq(model_1, "Normal-QQ plot")

mtext("Residualplottar för modell med alla \n förklarande variabler (period 1)", side = 3, line = 0, outer = TRUE, font = 2)
```


```{r, echo=FALSE, fig.cap="I de flesta plottarna ser vi att residualerna verkar ha en hyfsat jämn spridning runt residualer = 0, det finns inte heller några uppenbara samband mellan residualer och de förklarande variablerna. Möjligtvis att plotten med residualer mot religiositet visar ett potentiellt samband, men då vi har så få observationer är det svårt att avgöra."}
par(mfrow = c(2,3), mar = c(5,4,4,2)-0.2, oma = c(0,0,2.3,0), cex.lab=0.9)
plot(residuals(model_1) ~ data_1$arblös_män, 
     xlab = "arbetslöshetsindex män",
     ylab = "residualer",
     main = "Mot arbetslöshet (män)")
abline(0,0)
plot(residuals(model_1) ~ data_1$arblös_tot, 
     xlab = "arbetslöshetsindex total",
     ylab = "",
     main = "Mot arbetslöshet (total)")
abline(0,0) 
plot(residuals(model_1) ~ data_1$alko, 
     xlab = "alkoholindex",
     ylab = "",
     main = "Mot alkohol")
abline(0,0) 
plot(residuals(model_1) ~ data_1$urban, 
     xlab = "urbaniseringsindex",
     ylab = "residualer",
     main = "Mot urbanisering")
abline(0,0) 
plot(residuals(model_1) ~ data_1$skilsmässo, 
     xlab = "skilsmässoindex",
     ylab = "",
     main = "Mot skilsmässor")
abline(0,0) 
plot(residuals(model_1) ~ data_1$religio, 
     xlab = "religiositetsindex",
     ylab = "",
     main = "Mot religiositet")
abline(0,0)

mtext("Residualplottar för modell med alla förklarande variabler (period 1)", side = 3, line = -1, outer = TRUE, font = 2)
```


# Översiks residualer period 2

```{r, echo=FALSE, fig.cap="Residualerna mot predikterade värden ser ganska bra ut, vi kan inte se någon tydlig heteroskedasticitet. Däremot finns det en antydan till icke-linjäritet (vid predikerade värden på ca. 35 till 55). Vi kan alltså se es viss heteroskedasticitet hos residualerna. Normal QQ-plotten ser okej ut, det är svårt att avgöra då vi har en begränsad mängd data. Vi bedömer dock att residualerna åtminstone ser approximativt normalfördelade ut."}
par(mfrow = c(1,2), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
plot_predicted_residuals(model_2, "Mot predikterade")
plot_qq(model_2, "Normal-QQ plot")

mtext("Residualplottar för modell med alla \n förklarande variabler (period 2)", side = 3, line = 0, outer = TRUE, font = 2)
```


```{r, echo=FALSE, fig.cap="I de flera plottarna ser vi att residualerna verkar ha en hyfsat jämn spridning runt residualer = 0. Det finns möjligtvis något samband mellan residualerna och de förklarande variablerna för skilsmässor och religiositet. Detta är återigen svårt att avgöra då vi har så få observationer är det svårt att avgöra. "}
par(mfrow = c(2,3), mar = c(5,4,4,2)-0.2, oma = c(0,0,2.3,0), cex.lab=0.9)
plot(residuals(model_2) ~ data_2$arblös_män, 
     xlab = "arbetslöshetsindex män",
     ylab = "residualer",
     main = "Mot arbetslöshet (män)")
abline(0,0)
plot(residuals(model_2) ~ data_2$arblös_tot, 
     xlab = "arbetslöshetsindex total",
     ylab = "",
     main = "Mot arbetslöshet (total)")
abline(0,0) 
plot(residuals(model_2) ~ data_2$alko, 
     xlab = "alkoholindex",
     ylab = "",
     main = "Mot alkohol")
abline(0,0) 
plot(residuals(model_2) ~ data_2$urban, 
     xlab = "urbaniseringsindex",
     ylab = "residualer",
     main = "Mot urbanisering")
abline(0,0) 
plot(residuals(model_2) ~ data_2$skilsmässo, 
     xlab = "skilsmässoindex",
     ylab = "",
     main = "Mot skilsmässor")
abline(0,0) 
plot(residuals(model_2) ~ data_2$religio, 
     xlab = "religiositetsindex",
     ylab = "",
     main = "Mot religiositet")
abline(0,0)

mtext("Residualplottar för modell med alla förklarande variabler (period 2)", side = 3, line = -1, outer = TRUE, font = 2)
```

```{r, echo=FALSE}
new_data_2 <- data_2 %>% mutate(sjmo2 = sqrt(sjmo)) 

new_model_2 <- lm(data = new_data_2, sjmo2~.)
```

```{r, echo=FALSE, fig.cap="Vi kan se att det misstänkta sambandet i plotten för residualer mot predikterade värden i figur (???) inte längre finns kvar. Plotten för residualer mot predikterade värden ser dock inte helt homoskedastisk ut, det ser ut att finnas en viss bågform hos residualerna. Normal-QQ plotten ser inte heller ut att ha förbättrats särskilt mycket från figur (???)."}
par(mfrow = c(1,2), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
plot_predicted_residuals(new_model_2, "Mot predikterade")
plot_qq(new_model_2, "Normal-QQ plot")

mtext("Residualplottar för modell med alla \n förklarande variabler och kvadratroten ur självmordsfrekvensen som responsvariabel (period 2)", side = 3, line = 0, outer = TRUE, font = 2)
```


```{r, echo=FALSE, fig.cap="Residualerna ser bra ut för de flesta förklarande variabler. Spridningen är hyfsat jämn runt residualer = 0 och det går inte att urskilja något tydligt samband mellan residualerna och  respektive förklarande variabel."}
par(mfrow = c(2,3), mar = c(5,4,4,2)-0.2, oma = c(0,0,2.3,0), cex.lab=0.9)
plot(residuals(new_model_2) ~ new_data_2$arblös_män, 
     xlab = "arbetslöshetsindex män",
     ylab = "residualer",
     main = "Mot arbetslöshet (män)")
abline(0,0)
plot(residuals(new_model_2) ~ new_data_2$arblös_tot, 
     xlab = "arbetslöshetsindex total",
     ylab = "",
     main = "Mot arbetslöshet (total)")
abline(0,0) 
plot(residuals(new_model_2) ~ new_data_2$alko, 
     xlab = "alkoholindex",
     ylab = "",
     main = "Mot alkohol")
abline(0,0) 
plot(residuals(new_model_2) ~ new_data_2$urban, 
     xlab = "urbaniseringsindex",
     ylab = "residualer",
     main = "Mot urbanisering")
abline(0,0) 
plot(residuals(new_model_2) ~ new_data_2$skilsmässo, 
     xlab = "skilsmässoindex",
     ylab = "",
     main = "Mot skilsmässor")
abline(0,0) 
plot(residuals(new_model_2) ~ new_data_2$religio, 
     xlab = "religiositetsindex",
     ylab = "",
     main = "Mot religiositet")
abline(0,0)

mtext("Residualplottar för modell med alla förklarande variabler och \nkvadratroten ur självmordsfrekvensen som responsvariabel (period 2) ", side = 3, line = -1, outer = TRUE, font = 2)
```

# 2.3 residualer model_1c

```{r, echo=FALSE}
par(mfrow = c(2,3), mar = c(5,4,4,2)-0.2, oma = c(0,0,2.3,0), cex.lab=0.9)
plot_predicted_residuals(model_1c, "Mot predikterade")
plot_qq(model_1c, "Normal-QQ plot")

plot.new()

plot(residuals(model_1c) ~ data_1$arblös_tot, 
     xlab = "arbetslöshetsindex total",
     ylab = "residualer",
     main = "Mot arbetslöshet")
abline(0,0) 
plot(residuals(model_1c) ~ data_1$alko, 
     xlab = "alkoholindex",
     ylab = "",
     main = "Mot alkohol")
abline(0,0) 
plot(residuals(model_1c) ~ data_1$religio, 
     xlab = "religiositetsindex",
     ylab = "",
     main = "Mot religiositet")
abline(0,0)

mtext("Residualplottar för modell med alkohol, \n arbetslöshet (total) och religiositet (period 1)", side = 3, line = -1, outer = TRUE, font = 2)
```

# 3.5 residualer model_2e

```{r, echo=FALSE, fig.cap="" }
par(mfrow = c(2,3), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
plot_predicted_residuals(model_2e, "Residualer mot prediktrade")
plot_qq(model_2e, "Normal-QQ plot")

plot(residuals(model_2e) ~ data_2$arblös_tot, 
     xlab = "arbetslöshetsindex total",
     ylab = "residualer",
     main = "Mot arbetslöshet")
abline(0,0) 
plot(residuals(model_2e) ~ data_2$urban, 
     xlab = "urbaniseringsindex",
     ylab = "residualer",
     main = "Mot urbanisering")
abline(0,0) 
plot(residuals(model_2e) ~ data_2$skilsmässo, 
     xlab = "skilsmässoindex",
     ylab = "",
     main = "Mot skilsmässor")
abline(0,0) 
plot(residuals(model_2e) ~ data_2$religio, 
     xlab = "religiositetsindex",
     ylab = "",
     main = "Mot religiositet")
abline(0,0)

mtext("Residualplottar för modell med urbaniering, arbetslöshet (total), \n skilsmässor och religiositet (period 2)", side = 3, line = - 1, outer = TRUE, font = 2)
```

# residuals model_2c

```{r, echo=FALSE}
par(mfrow = c(2,3), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
plot_predicted_residuals(model_2c, "Mot predikterade")
plot_qq(model_2c, "Normal-QQ plot")

plot.new()

plot(residuals(model_2c) ~ data_2$alko, 
     xlab = "alkoholindex",
     ylab = "residuals",
     main = "Mot alkohol")
abline(0,0) 
plot(residuals(model_2c) ~ data_2$urban, 
     xlab = "urbaniseringsindex",
     ylab = "",
     main = "Mot urbanisering")
abline(0,0) 

mtext("Residualplottar för modell med alkohol och urbaniering (period 2)", side = 3, line = 0, outer = TRUE, font = 2)
```

# residualer model_1d_red

```{r}
par(mfrow = c(2,3), mar = c(5,4,4,2), oma = c(0,0,2,0), cex.lab=0.9)
plot_predicted_residuals(model_1d_red, "Residualer mot prediktrade")
plot_qq(model_1d_red, "Normal-QQ plot")

plot(residuals(model_1d_red) ~ data_1_red$arblös_män, 
     xlab = "arbetslöshetsindex män",
     ylab = "residualer",
     main = "Mot arbetslöshet")
abline(0,0) 
plot(residuals(model_1d_red) ~ data_1_red$urban, 
     xlab = "urbaniseringsindex",
     ylab = "residualer",
     main = "Mot urbanisering")
abline(0,0) 
plot(residuals(model_1d_red) ~ data_1_red$skilsmässo, 
     xlab = "skilsmässoindex",
     ylab = "",
     main = "Mot skilsmässor")
abline(0,0) 
plot(residuals(model_1d_red) ~ data_1_red$religio, 
     xlab = "religiositetsindex",
     ylab = "",
     main = "Mot religiositet")
abline(0,0)

mtext("Residualplottar för modell med urbaniering, arbetslöshet (män), \n skilsmässor och religiositet (period 1, utan Jönköping)", side = 3, line = - 1, outer = TRUE, font = 2)
```
